version: '3'
services:
  mongo:
    container_name: mongo
    build: .
    image: edmitry/mongo
    restart: always
    volumes:
      - mongo_data:/data/db
      - .:/app
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
volumes:
  mongo_data:
    external: true
