version: '3'
services:
  mongo:
    container_name: mongo
    build: .
    image: edmitry/mongo
    restart: always
    volumes:
      - mongo_data:/data/db
      - .:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
volumes:
  mongo_data:
    external: true
